### PR TITLE
Add support for Wii, Wii U, Ouya, and Vita

### PR DESCRIPTION
**Pull request by halotroop2288**
These platforms are already in the device list, and are already supported by Xelu's icon pack, so why not?
The same goes for the disconnected icon. Why not?

Additional changes:

- Rearrange the device list by category -> type -> generation
- Make the mapping script more D.R.Y by adding common methods for button layouts
- Reformat the DOCS.md tables using IntelliJ IDEA
- Rename incorrectly named icon files

### CODE REVIEW

**Comment by rsubtil** [comment]
Thank you for your contribution. While I initially intended to add those platforms since they were available in Xelu's pack, I actually removed them before the first release for a couple of reasons:

- Some platform controllers are not plug-and-play for PC. Wii U and Vita, for example, require third-party drivers/software to be used on PC, and even if there's a more reliable solution (e.g. Steam), they usually get mapped to Xbox 360 and thus this addon cannot automatically detect them.
- It's rare to see users with these controllers for PC gaming, thus it would "bloat" the addon with unnecessary assets. For those cases, the addon is designed to allow [detecting those controllers](https://github.com/rsubtil/controller_icons/blob/master/DOCS.md#changing-controller-mapper) and [adding assets to them](https://github.com/rsubtil/controller_icons/blob/master/DOCS.md#addingremoving-controller-icons) without any core modification.
- This addon is intended for PC game development, where many different controller can be used. However, it's only useful for mostly "standardized" layouts with only small tweaks to button placement and icons. For more exotic controllers like the Wii, a 1:1 mapping is impossible, and since games would have to be designed specifically for that controller type, it would defeat the need for this addon anyways.

So, adding support for **Wii**, **Wii U** and **Vita** is not a good idea. With that said, **OUYA** does pass the above conditions, so it can be added :+1:

> Actually, speaking of making the Mapper script more D.R.Y., why isn't it using dictionaries instead of if-else chains and multiple functions that do the same thing?

While dictionaries make the code cleaner and easier to read, they're less performant to use than enums. The Mapper class is called from every icon on load, and whenever a controller is plugged/unplugged, so performance is important here.

**Comment by halotroop2288** [comment]
Designing an addon for a multi-platform engine, for only one platform seems kind of terrible. But hey whatever. Like I said I kind of wanted to rewrite it anyway.

Good luck, and feel free to snip my code. I'll leave the branch up for a while.

**Comment by rsubtil** [comment]
> Designing an addon for a multi-platform engine, for only one platform seems kind of terrible.

There is no point in using this addon for console development, since the compatible controllers are tied to the brand (you can't use Nintendo controllers on an Xbox or PlayStation, for example). It is only useful for newer platforms that offer controller backward-compatibility (Xbox Series supporting Xbox One controller, for instance), but even then that's a weak argument. Not to mention this is all assuming Godot even runs on these suggested platforms, which it doesn't (except OUYA since it's Android based, therefore why I agree it can be added).

The other parts of your PR (code cleanup and refactoring) are valid though, so if you want to contribute those, feel free to reopen this PR or make another one with those. I don't "snip" code because that would take away credit from you, the author.

**Comment by halotroop2288** [comment]
> since the compatible controllers are tied to the brand (you can't use Nintendo controllers on an Xbox or PlayStation, for example)

That's a flaw in your design. It doesn't check `OS.get_name()` before detecting controller type. People are still designing games for multiple platforms. They're not all exclusives. In fact we're getting fewer platform-exclusive titles than ever now.

1. Check which platform you're on, then assume you're using a specific controller or set of controllers if you're on one with only one controller.
2. If you're on a platform with multiple controller configurations, you move on to detecting a subset of the controller types. (Switch has Pro, single-con, multi-con grip, handheld. Most gen-6+ consoles also support mostly-compatible gimmick controllers for Rock Band, Guitar Hero, etc.)
3. If you're on desktop, web, or mobile, you move on to detecting any controller type.

This reduces the amount of checking on some consoles considerably. I'm already implementing this in my library, which uses a mix of different authors' open-license prompts to fill in more support gaps.

**Comment by rsubtil** [comment]
*(sorry for the late reply, got busy with other stuff these last few days)*

> That's a flaw in your design. It doesn't check OS.get_name() before detecting controller type. People are still designing games for multiple platforms. They're not all exclusives. In fact we're getting fewer platform-exclusive titles than ever now.

I don't see it as a design flaw, but rather a design choice. I've never worked with consoles and even if I wanted this addon to support them I have no feasible way to do that without getting access to a version of Godot designed for consoles, which would involve getting in contact with companies that [offer those services](https://docs.godotengine.org/en/stable/tutorials/platform/consoles.html). It's also likely that consoles provide specific APIs to detect what controller type is active, but again, I have no way of knowing all of this as a "hobby" project, so console support is not a priority right now.

> Also, you don't need to be running detect every frame. Only once per device connection event. It doesn't actually create that much overhead if you do it right.

The addon is using a signal to detect device changes already:
https://github.com/rsubtil/controller_icons/blob/f57beb4e2da6891e823effdcb5313341a08f4a3c/addons/controller_icons/ControllerIcons.gd#L87-L88

> Regarding code-snipping, I would accept a co-author tag on your commits if you'd like. It's easier for you to know exactly what you want to leave or take and just do it. :)

Alright, in that case I'll add a co-author field, but I need to know [your e-mail](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#required-co-author-information) for that (you can share the GitHub's `no-reply` email to avoid sharing your personal email).

**Pull request closed without merging**
